name: Release

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Release with Semantic Release
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release
